language: node_js
before_script:
  - npm install -g gatsby-cli
  - yarn install
  - yarn build
  - ls -la
node_js:
  - "10"

deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
